### ISSUE TITLE
Make the RPC call as property access on the Proxy?

### ISSUE THREAD

**Issue by esamattis** [KATT/trpc-procedure-play#19]
Since you are using JS Proxies why not go all in and implement the rpc calls directly as a property access? 

Eg. instead of

```js
client.query(queries.greeting, {hello: 'string'})
```

why not allow

```js
client.greeting({hello: 'string'})
```

Although with this it could be trickier for the go-to-definition implementation.

**Comment by esamattis** [comment]
Also one could argue that "dotted" queries are uglier with this

```ts
client["todo.add"]({task: 'string'})
```

Personally I don't care. I'd just stay with camel casing.

**Comment by KATT** [comment]
> Also one could argue that "dotted" queries are uglier with this
> 
> ```ts
> client["todo.add"]({task: 'string'})
> ```
> 
> Personally I don't care. I'd just stay with camel casing.

See https://github.com/trpc/v10-playground/issues/6#issuecomment-1018998345

**Comment by KATT** [comment]
> Eg. instead of
> 
> ```js
> client.query(queries.greeting, {hello: 'string'})
> ```
> 
> why not allow
> 
> ```js
> client.greeting({hello: 'string'})
> ```
I will have a play with this!

**Comment by KATT** [comment]
Closing in favor of #26
