### ISSUE TITLE
Double model definition

### ISSUE THREAD

**Issue by iceydee** [KATT/trpc-procedure-play#9]
https://github.com/trpc/v10-playground/blob/b3e2372b62679353dfdcad8a7e69040f6ede0f94/src/server.ts#L62-L65

Why do I need to define the input model twice? It's already in the zod part. Feels like "cake on cake".

**Comment by KATT** [comment]
the `expectTypeOf()` is only for asserting that the inference is doing what it's intended to. More clear now that I moved it to another file called `.test.ts`? https://github.com/trpc/v10-playground/blob/c104f0890eab49a19ff7f1d638c6a199c1a9eb0e/src/server.test.ts#L53-L60
